bincheck: print error messages on stderr

diff --git a/.local/bin/bincheck b/.local/bin/bincheck
--- a/.local/bin/bincheck
+++ b/.local/bin/bincheck
@@ -7,7 +7,10 @@ exit_status=0
 # Check installed binaries
 binaries=$(jq -r '.[]' ~/.config/scripts/setup/binaries.json)
 while read -r bin || [ -n "$bin" ]; do
-    command -v "$bin" >/dev/null 2>&1 || { echo "$bin cannot be found in \$PATH" && exit_status=1; }
+    command -v "$bin" >/dev/null 2>&1 || {
+        echo "$bin cannot be found in \$PATH" >&2
+        exit_status=1
+    }
 done <<EOF
 $binaries
 EOF
@@ -15,7 +18,10 @@ EOF
 # Check fstab entries
 entry_patterns=$(jq -r '.[]' ~/.config/scripts/setup/fstab.json)
 while read -r pattern || [ -n "$pattern" ]; do
-    grep -qE "$pattern" /etc/fstab || { echo 'Entry missing from /etc/fstab' && exit_status=1; }
+    grep -qE "$pattern" /etc/fstab || {
+        echo 'Entry missing from /etc/fstab' >&2
+        exit_status=1
+    }
 done <<EOF
 $entry_patterns
 EOF
@@ -23,7 +29,10 @@ EOF
 # Check enabled systemd user units
 enabled_user_units=$(jq -r '.[]' ~/.config/scripts/setup/systemd-user.json)
 while read -r unit || [ -n "$unit" ]; do
-    systemctl -q --user is-enabled "$unit" || { echo "$unit is not enabled" && exit_status=1; }
+    systemctl -q --user is-enabled "$unit" || {
+        echo "$unit is not enabled" >&2
+        exit_status=1
+    }
 done <<EOF
 $enabled_user_units
 EOF
@@ -31,7 +40,10 @@ EOF
 # Check enabled systemd system units
 enabled_system_units=$(jq -r '.[]' ~/.config/scripts/setup/systemd-system.json)
 while read -r unit || [ -n "$unit" ]; do
-    systemctl -q is-enabled "$unit" || { echo "$unit is not enabled" && exit_status=1; }
+    systemctl -q is-enabled "$unit" || {
+        echo "$unit is not enabled" >&2
+        exit_status=1
+    }
 done <<EOF
 $enabled_system_units
 EOF
